spring:
  datasource:
    username: sa
#    url: jdbc:sqlserver://192.168.50.1:1433;DatabaseName=DB_DESIGN
#    password: zw1234aA#
#    url: jdbc:sqlserver://192.168.72.229:1433;DatabaseName=DB_DESIGN
#    password: 123
    url: jdbc:sqlserver://192.168.72.155:1433;DatabaseName=DB_DESIGN
    password: zw1234aA#
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  cache:
    type: redis
  redis:
#    host: 192.168.50.1
    host: 192.168.72.158
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zw.design.entity.dbo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true
logging:
#  level:
#    root: warn
  path: e:/DesignProjectLog
upload:
  path: e:/upload/
  temp: e:/upload/__temp/
server:
  servlet:
    session:
      timeout: 3600s
